name: "Test linux"

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['python']
        python-version: ["3.10"]
        architecture: ["x64"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v3.0.0
      with:
        languages: ${{ matrix.language }}
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
        cache: pip
        
    - name: install modules
      run: python -m pip install wheel pillow tkinterweb psutil
      
    - name: install xorg
      run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev dbus-x11 ghostscript python3-tk
      
    - run: Xvfb :1 -screen 0 1600x1200x24 &
    - run: export DISPLAY=:1.0
    - run: python3 OS.py

