name: "Test linux"

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['python']
        python-version: ["3.10"]
        architecture: ["x64"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v3.0.0
      with:
        languages: ${{ matrix.language }}
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
        cache: pip
        
    - name: install modules
      run: python -m pip install wheel pillow tkinterweb psutil
      
    - name: display
      run: export DISPLAY=:0.0
      
    - name: execute and get logs
      run: python OS.py

